### ISSUE TITLE
Suggestion: Allow different event targets

### ISSUE THREAD

**Issue by desislavsd** [shentao/vue-global-events#13]
It would be cool if I can specify different event target other than `document` like `window` and `body`. Probably using modifiers or arguments with the bindings: ` @scroll.window`, `@scroll:body`.

**Comment by shentao** [comment]
This is an interesting idea, though probably it would be easier to do by using a prop like `target="window"` rather than a modifier since it would save us some code required to parse them. And there is no problem with just using two global-events components next to each other. One for window and one for document.

**Comment by posva** [comment]
Yes, this would go on a prop. It's weird, I though we had an open issue about this. I'm sure I talked about having different targets with someone haha
