### ISSUE TITLE
bubbling event is not fired on IE.

### ISSUE THREAD

**Issue by ta-kiyama** [shentao/vue-global-events#14]
On IE, the third arguments of EventTarget#addEventListener is only supported for type of Boolean.

Therefore, all of global events dispatch as capture event on IE because object (and empty object) is truthy value.

https://github.com/shentao/vue-global-events/blob/master/src/index.js#L9-L15

**Comment by ta-kiyama** [comment]
I suggest the below table.  
This table shows the input modifier of `capture`, `once`, and `passive` and output result value.

| capture | once | passive | result |
|:-------:|:----:|:-------:|:------:|
| false | false | false | false |
| false | false | true  | { passive: true } |
| false | true  | false | { once: true } |
| false | true  | true  | { once: true, passive: true } |
| true  | false | false | true |
| true  | false | true  | { capture: true, passive: true } |
| true  | true  | false | { capture: true, once: true } |
| true  | true  | true  | { capture: true, once: true, passive: true } |

**Comment by posva** [comment]
Can you provide a minimal repro of what you mean? (the content of an HTML file would be the best). Also what version of IE are you referring to?

**Comment by posva** [comment]
I see, since IE only supports the Boolean version of it (for capture). I think it's better to only take into account the `capture` modifier and return it (undefined or true) when the current browser is IE. That would be much easier and small 🙂 . Feel free to do a PR for this (with a test) if you want. Otherwise I will probably pick it up later in the day

**Comment by ta-kiyama** [comment]
@posva Sorry for my late reply. I send PR. Could you review it when you have a time?
