### ISSUE TITLE
Keyup for shift and ctrl modifiers does not work in the latest 3.0.0 version

### ISSUE THREAD

**Issue by S-h-a-m-o-t** [shentao/vue-global-events#291]
### Reproduction

https://jsfiddle.net/25yx04oq/

### Steps to reproduce the bug

We have used this code with Vue 2 and worked fine. Now with Vue 3 @keyup.17 and @keyup.16 does not trigger any more.

`<script src="https://unpkg.com/vue@3"></script>
<script src="https://unpkg.com/vue-global-events@2"></script>

<div id="app">
  <global-events
    @keydown.ctrl="isControl = true"
    @keyup.17="isControl = false"
    @keydown.shift="isShift = true"
    @keydown.16="isShift = false"
  ></global-events>
  <h1>
  Ctrl and Shift demo
  </h1>
  <dl>
    <dt>Control: <span>{{ isControl }}</span><dt>
    <dt>Shift: <span>{{ isShift }}</span><dt>
  </dl>
</div>

const { createApp } = Vue

createApp({
	el: '#app',
	components: {
  	GlobalEvents: VueGlobalEvents.GlobalEvents
  },
  data: () => ({
    isControl: false,
    isShift: false,
  })
}).mount('#app')`

### Expected behavior

@keyup.16 and @keyup.17 should be trigerred

### Actual behavior

@keyup.16 and @keyup.17 are not trigerred

### Additional information

@keydown.control and @keyup.control is triggered correctly. Is there a similar option for shift key?

**Comment by posva** [comment]
This is the same in plain vue. It's more about `ctrl` being a modifier and keyup not having that modifier because you are releasing the ctrl key. You can [use `control` instead](https://play.vuejs.org/#eNp9UctOwzAQ/JXFl4BUUqHeqrTioUrAARAgcfGlSrdJWse27HUpivLvrF0aOKDevDOz4xltJ26szXcBxVQUvnSNJfBIwc6lblprHEEHDtfQw9qZFjKWZlJLXRrtCVpfwSzy59k9KmXgwzi1OssupC7GBzs24oGwtWpJyBNAUV/Nuy4t930x5imhjbaBYHfZmhWqmRTMSwHXW/wKNuf/yJkfGGZZbWqTScGbxXgwFyNBnpXrpso33mgu1UVrKUrT2kahe7bUcHIpppCYyC05+OdjwsgFHB3xssZy+w++8fuISfHi0KPboRQDR0tXIR3oxdsT7vk9kFwsKFafIF/RGxVixoPsNugVx/6jS2kf0mkaXb37xZ5Q+2OpGDQq+6SXgs91d6L6b9xJPkl7Uvei/wZIyrCx)

- You can check the `key` value for this: https://www.toptal.com/developers/keycode

**Comment by S-h-a-m-o-t** [comment]
Thanks. Yes, there is a solution for control as I have already mentioned in the issue. But for shift not. 
Since from the doc BREAKING: Using numbers, i.e. keyCodes, as v-on modifiers is no longer supported there is no solution for shift imho. 

Way to go is to check if ctrl / shift / alt key was pressed in the event parameter of the event handler.

Thanks.
